/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Sewa;

import Koneksi.koneksidb;
import java.sql.*;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
/**
 *
 * @author Acer
 */
public class formlaporan extends javax.swing.JFrame {

    /**
     * Creates new form formlaporan
     */
    public formlaporan() {
        initComponents();
    }
    
    public void lappetugas(){
        try {
        JasperPrint jp = JasperFillManager.fillReport(getClass().getResourceAsStream("lappetugas.jasper"), null, koneksidb.getKoneksi());
        JasperViewer.viewReport(jp, false);
        } catch(Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }
    
    public void lapproduk(){
        try {
        JasperPrint jp = JasperFillManager.fillReport(getClass().getResourceAsStream("lapproduk.jasper"), null, koneksidb.getKoneksi());
        JasperViewer.viewReport(jp, false);
        } catch(Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }
    
    public void lappenyewa(){
        try {
        JasperPrint jp = JasperFillManager.fillReport(getClass().getResourceAsStream("lappenyewa.jasper"), null, koneksidb.getKoneksi());
        JasperViewer.viewReport(jp, false);
        } catch(Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }
    
    public void lappeminjaman(){
        try {
        JasperPrint jp = JasperFillManager.fillReport(getClass().getResourceAsStream("lappeminjaman.jasper"), null, koneksidb.getKoneksi());
        JasperViewer.viewReport(jp, false);
        } catch(Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }
    
    public void lappengembalian(){
        try {
        JasperPrint jp = JasperFillManager.fillReport(getClass().getResourceAsStream("lappengembalian.jasper"), null, koneksidb.getKoneksi());
        JasperViewer.viewReport(jp, false);
        } catch(Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        laporanpenyewa = new javax.swing.JButton();
        laporanproduk = new javax.swing.JButton();
        laporanpetugas = new javax.swing.JButton();
        laporanpetugas1 = new javax.swing.JButton();
        laporanpetugas2 = new javax.swing.JButton();
        bkeluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        jLabel1.setText("LAPORAN SEWA KAMERA");

        laporanpenyewa.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        laporanpenyewa.setText("LAPORAN DATA PENYEWA");
        laporanpenyewa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporanpenyewaActionPerformed(evt);
            }
        });

        laporanproduk.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        laporanproduk.setText("LAPORAN DATA PRODUK");
        laporanproduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporanprodukActionPerformed(evt);
            }
        });

        laporanpetugas.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        laporanpetugas.setText("LAPORAN DATA PETUGAS");
        laporanpetugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporanpetugasActionPerformed(evt);
            }
        });

        laporanpetugas1.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        laporanpetugas1.setText("LAPORAN DATA PEMINJAMAN");
        laporanpetugas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporanpetugas1ActionPerformed(evt);
            }
        });

        laporanpetugas2.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        laporanpetugas2.setText("LAPORAN DATA PENGEMBALIAN");
        laporanpetugas2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporanpetugas2ActionPerformed(evt);
            }
        });

        bkeluar.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        bkeluar.setText("KELUAR");
        bkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bkeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(laporanpenyewa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(laporanproduk, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(laporanpetugas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(laporanpetugas1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(laporanpetugas2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bkeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(62, 62, 62))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addComponent(laporanpenyewa, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(laporanproduk, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(laporanpetugas, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(laporanpetugas1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(laporanpetugas2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(bkeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void laporanpenyewaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporanpenyewaActionPerformed
        // TODO add your handling code here:
        lappenyewa();
    }//GEN-LAST:event_laporanpenyewaActionPerformed

    private void laporanprodukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporanprodukActionPerformed
        // TODO add your handling code here:
        lapproduk();
    }//GEN-LAST:event_laporanprodukActionPerformed

    private void laporanpetugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporanpetugasActionPerformed
        // TODO add your handling code here:
        lappetugas();
    }//GEN-LAST:event_laporanpetugasActionPerformed

    private void laporanpetugas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporanpetugas1ActionPerformed
        // TODO add your handling code here:
        lappeminjaman();
    }//GEN-LAST:event_laporanpetugas1ActionPerformed

    private void laporanpetugas2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporanpetugas2ActionPerformed
        // TODO add your handling code here:
        lappengembalian();
    }//GEN-LAST:event_laporanpetugas2ActionPerformed

    private void bkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bkeluarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_bkeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formlaporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formlaporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formlaporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formlaporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formlaporan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bkeluar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton laporanpenyewa;
    private javax.swing.JButton laporanpetugas;
    private javax.swing.JButton laporanpetugas1;
    private javax.swing.JButton laporanpetugas2;
    private javax.swing.JButton laporanproduk;
    // End of variables declaration//GEN-END:variables
}
