/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Sewa;

/**
 *
 * @author Acer
 */
import Koneksi.koneksidb;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.util.logging.Level;
import java.util.logging.Logger;
        
public class formutama extends javax.swing.JFrame {
    ResultSet Data;
    String usernm,passwd,level;
public boolean berhasil = false;

    /**
     * Creates new form formutama
     */
    public formutama() {
        initComponents();
        
        enable();
    }
    
    public void enable(){
        bpetugas.hide();
        bkategori.hide();
        bproduk.hide();
        bpeminjaman.hide();
        bpengembalian.hide();
        blaporan.hide();
        bkeluar.hide();
        lstatus.hide();
        panelmenu.hide();
        panellogin.hide();
    }
    
    public boolean login() throws SQLException {
        if (cblevel.getSelectedItem().equals("Admin")) {
            try {
                Statement stat = (Statement) koneksidb.getKoneksi().createStatement();
                Data = stat.executeQuery("SELECT username, password FROM login "
                        + "WHERE username='"+usernm+"'"
                + "and password ='"+passwd+"'");
                berhasil = Data.next();
                    panellogin.hide();
                    bpetugas.setEnabled(true);
                    bkategori.setEnabled(true);
                    bproduk.setEnabled(true);
                    bpeminjaman.setEnabled(true);
                    bpengembalian.setEnabled(true);
                    blaporan.setEnabled(true);       
                    lstatus.setText("Admin");
            } catch (SQLException salah){
                System.out.println(salah);
            }
        } else if (cblevel.getSelectedItem().equals("Petugas")){
            try{
                Statement stat = (Statement) koneksidb.getKoneksi().createStatement();
                Data = stat.executeQuery("SELECT username, password FROM login "
                        +"WHERE username='"+usernm+"'"
                + "and password ='"+passwd+"'");
                berhasil = Data.next();
                    panellogin.hide();
                    bpetugas.setEnabled(true); 
                    bkategori.setEnabled(true); 
                    bproduk.setEnabled(true); 
                    bpeminjaman.setEnabled(true); 
                    bpengembalian.setEnabled(true); 
                    blaporan.setEnabled(false);
                    lstatus.setText("Petugas");
            } catch (SQLException salah){
                System.out.println(salah);
            }
        }
        return berhasil;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panellogin = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tusername = new javax.swing.JTextField();
        blogin = new javax.swing.JButton();
        bbatal = new javax.swing.JButton();
        cblevel = new javax.swing.JComboBox<>();
        tpassword = new javax.swing.JPasswordField();
        panelmenu = new javax.swing.JPanel();
        bpetugas = new javax.swing.JButton();
        bkategori = new javax.swing.JButton();
        bproduk = new javax.swing.JButton();
        bpeminjaman = new javax.swing.JButton();
        bpengembalian = new javax.swing.JButton();
        blaporan = new javax.swing.JButton();
        bkeluar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lstatus = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panellogin.setBackground(new java.awt.Color(153, 153, 255));

        jLabel4.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jLabel4.setText("SILAHKAN LOGIN!!!");

        jLabel3.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        jLabel3.setText("USERNAME");

        jLabel5.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        jLabel5.setText("PASSWORD");

        jLabel6.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        jLabel6.setText("LEVEL");

        blogin.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        blogin.setText("LOGIN");
        blogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bloginActionPerformed(evt);
            }
        });

        bbatal.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        bbatal.setText("BATAL");
        bbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbatalActionPerformed(evt);
            }
        });

        cblevel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Pilih Level-", "Admin", "Petugas" }));

        javax.swing.GroupLayout panelloginLayout = new javax.swing.GroupLayout(panellogin);
        panellogin.setLayout(panelloginLayout);
        panelloginLayout.setHorizontalGroup(
            panelloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelloginLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(panelloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelloginLayout.createSequentialGroup()
                        .addGroup(panelloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6))
                        .addGap(36, 36, 36)
                        .addGroup(panelloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tusername)
                            .addComponent(cblevel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelloginLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel4)))
                .addContainerGap(54, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelloginLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(blogin, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bbatal, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
        );
        panelloginLayout.setVerticalGroup(
            panelloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelloginLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel4)
                .addGap(31, 31, 31)
                .addGroup(panelloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tusername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cblevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(panelloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(blogin, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bbatal, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        panelmenu.setBackground(new java.awt.Color(153, 153, 255));

        bpetugas.setBackground(new java.awt.Color(102, 102, 255));
        bpetugas.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        bpetugas.setText("PETUGAS");
        bpetugas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bpetugasMouseClicked(evt);
            }
        });
        bpetugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bpetugasActionPerformed(evt);
            }
        });

        bkategori.setBackground(new java.awt.Color(102, 102, 255));
        bkategori.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        bkategori.setText("PENYEWA");
        bkategori.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bkategoriMouseClicked(evt);
            }
        });
        bkategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bkategoriActionPerformed(evt);
            }
        });

        bproduk.setBackground(new java.awt.Color(51, 102, 255));
        bproduk.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        bproduk.setText("PRODUK");
        bproduk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bprodukMouseClicked(evt);
            }
        });
        bproduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bprodukActionPerformed(evt);
            }
        });

        bpeminjaman.setBackground(new java.awt.Color(102, 102, 255));
        bpeminjaman.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        bpeminjaman.setText("PEMINJAMAN");
        bpeminjaman.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bpeminjamanMouseClicked(evt);
            }
        });
        bpeminjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bpeminjamanActionPerformed(evt);
            }
        });

        bpengembalian.setBackground(new java.awt.Color(102, 102, 255));
        bpengembalian.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        bpengembalian.setText("PENGEMBALIAN");
        bpengembalian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bpengembalianMouseClicked(evt);
            }
        });
        bpengembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bpengembalianActionPerformed(evt);
            }
        });

        blaporan.setBackground(new java.awt.Color(102, 102, 255));
        blaporan.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        blaporan.setText("LAPORAN");
        blaporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                blaporanMouseClicked(evt);
            }
        });
        blaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blaporanActionPerformed(evt);
            }
        });

        bkeluar.setBackground(new java.awt.Color(102, 102, 255));
        bkeluar.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        bkeluar.setText("KELUAR");
        bkeluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bkeluarMouseClicked(evt);
            }
        });
        bkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bkeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelmenuLayout = new javax.swing.GroupLayout(panelmenu);
        panelmenu.setLayout(panelmenuLayout);
        panelmenuLayout.setHorizontalGroup(
            panelmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelmenuLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(bpetugas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bkategori)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(blaporan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bproduk, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelmenuLayout.createSequentialGroup()
                        .addComponent(bpeminjaman)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bpengembalian))
                    .addComponent(bkeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        panelmenuLayout.setVerticalGroup(
            panelmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelmenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bpetugas, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bkategori, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bproduk, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bpeminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bpengembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(blaporan, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bkeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Calisto MT", 1, 24)); // NOI18N
        jLabel2.setText("MENU");

        jLabel1.setFont(new java.awt.Font("Calisto MT", 1, 24)); // NOI18N
        jLabel1.setText("SISTEM PERSEWAAN KAMERA");

        lstatus.setText("status");

        jMenu1.setText("Menu");

        jMenuItem1.setText("Login");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Keluar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(302, 302, 302)
                        .addComponent(jLabel2))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(164, 164, 164)
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lstatus))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(panelmenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panellogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(170, 170, 170))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lstatus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelmenu, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panellogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbatalActionPerformed
        // TODO add your handling code here:
        panellogin.setVisible(false);
    }//GEN-LAST:event_bbatalActionPerformed

    private void bloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bloginActionPerformed
        // TODO add your handling code here:
        usernm = tusername.getText();
        passwd = tpassword.getText();
        
        try {
            login();
        } catch (SQLException ex) {
            Logger.getLogger(formutama.class.getName()).log(Level.SEVERE, null, ex);
        }
        panelmenu.setVisible(true);
        lstatus.show();
        bkeluar.setVisible(true);
        bpetugas.setVisible(true);
        bkategori.setVisible(true);
        bproduk.setVisible(true);
        bpeminjaman.setVisible(true);
        bpengembalian.setVisible(true);
        blaporan.setVisible(true);
    
    }//GEN-LAST:event_bloginActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        panellogin.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void bkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bkeluarActionPerformed
        // TODO add your handling code here:
        panellogin.setVisible(true);
        panelmenu.hide();
        tusername.setText("");
        tpassword.setText("");
        lstatus.hide();
        bproduk.hide();
        bpetugas.hide();
        bkategori.hide();
        bpeminjaman.hide();
        bpengembalian.hide();
        blaporan.hide();
    }//GEN-LAST:event_bkeluarActionPerformed

    private void bkeluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bkeluarMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_bkeluarMouseClicked

    private void blaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blaporanActionPerformed
        // TODO add your handling code here:
        new formlaporan().setVisible(true);
    }//GEN-LAST:event_blaporanActionPerformed

    private void blaporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_blaporanMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_blaporanMouseClicked

    private void bpengembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bpengembalianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bpengembalianActionPerformed

    private void bpengembalianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bpengembalianMouseClicked
        // TODO add your handling code here:
        new formtransaksikembali().setVisible(true);
    }//GEN-LAST:event_bpengembalianMouseClicked

    private void bpeminjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bpeminjamanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bpeminjamanActionPerformed

    private void bpeminjamanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bpeminjamanMouseClicked
        // TODO add your handling code here:
        new formTransaksi().setVisible(true);
    }//GEN-LAST:event_bpeminjamanMouseClicked

    private void bprodukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bprodukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bprodukActionPerformed

    private void bprodukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bprodukMouseClicked
        // TODO add your handling code here:
        new formproduk().setVisible(true);
    }//GEN-LAST:event_bprodukMouseClicked

    private void bkategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bkategoriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bkategoriActionPerformed

    private void bkategoriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bkategoriMouseClicked
        // TODO add your handling code here:
        new formpenyewa().setVisible(true);
    }//GEN-LAST:event_bkategoriMouseClicked

    private void bpetugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bpetugasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bpetugasActionPerformed

    private void bpetugasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bpetugasMouseClicked
        // TODO add your handling code here:
        new formpetugas().setVisible(true);
    }//GEN-LAST:event_bpetugasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formutama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formutama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formutama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formutama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formutama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bbatal;
    private javax.swing.JButton bkategori;
    private javax.swing.JButton bkeluar;
    private javax.swing.JButton blaporan;
    private javax.swing.JButton blogin;
    private javax.swing.JButton bpeminjaman;
    private javax.swing.JButton bpengembalian;
    private javax.swing.JButton bpetugas;
    private javax.swing.JButton bproduk;
    private javax.swing.JComboBox<String> cblevel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JLabel lstatus;
    private javax.swing.JPanel panellogin;
    private javax.swing.JPanel panelmenu;
    private javax.swing.JPasswordField tpassword;
    private javax.swing.JTextField tusername;
    // End of variables declaration//GEN-END:variables
}
